# Nuitka Configuration for PDF Duplicate Finder v3.0.0
# This configuration file is used for Nuitka builds

[general]
# General build settings
version = "3.0.0"
company_name = "Tuxxle"
product_name = "PDF Duplicate Finder"
file_description = "Find and manage duplicate PDF files"
copyright = "© 2025 Nsfr750 - All rights reserved"
website = "https://github.com/Nsfr750/PDF_finder"

[build]
# Build configuration
standalone = true
onefile = true
follow_imports = true
follow_stdlib = true
remove_output = true
assume_yes_for_downloads = true

[windows]
# Windows-specific settings
icon = "assets/icon.ico"
console_mode = false
disable_console = true
file_version = "3.0.0.0"
product_version = "3.0.0.0"

[linux]
# Linux-specific settings
console_mode = true
lto = true
jobs = 8

[macos]
# macOS-specific settings
console_mode = false

[includes]
# Packages to include
packages = [
    "tqdm",
    "send2trash",
    "psutil",
    "PyQt6",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "PyQt6.QtPrintSupport",
    "PyQt6.QtSvg",
    "PyQt6.QtPdf",
    "PyQt6.QtPdfWidgets",
    "PyQt6.QtWebEngine",
    "PyQt6.QtWebEngineWidgets"
]

[data_files]
# Data files to include
files = [
    "assets/icon.ico=assets/icon.ico",
    "assets/logo.png=assets/logo.png",
    "assets/version_info.txt=assets/version_info.txt",
    "config/settings.json=config/settings.json",
    "config/updates.json=config/updates.json"
]

[data_dirs]
# Data directories to include
directories = [
    "assets=assets",
    "config=config",
    "script/lang=script/lang"
]

[excludes]
# Packages to exclude
packages = [
    "*.tests",
    "*.test",
    "*.unittest",
    "*.setuptools",
    "*.distutils",
    "*.pkg_resources",
    "*.pytest",
    "*.setuptools_rust",
    "scipy",
    "skimage",
    "PIL",
    "tkinter"
]

[plugins]
# Nuitka plugins to enable
enabled = ["pyqt6"]

[output]
# Output settings
output_dir = "dist"
windows_filename = "PDF-Finder_3.0.0"
linux_filename = "PDFDuplicateFinder-3.0.0-linux"
macos_filename = "PDFDuplicateFinder-3.0.0-macos"

[optimization]
# Optimization settings
follow_imports = true
follow_stdlib = true
nofollow_import_to = [
    "*.tests",
    "*.test",
    "*.unittest",
    "*.setuptools",
    "*.distutils",
    "*.pkg_resources",
    "*.pytest",
    "*.setuptools_rust"
]

[debugging]
# Debugging settings
debug = false
unstripped = false
profile = false

[deployment]
# Deployment settings
no_deployment_flag = true
python_flag = "no_site"
